[config-manager] --setopt: Fix crash with "--save --dump" (RhBug:1702678)
Removes useless code which only causes crash.

Example of crash:
dnf config-manager --save --dump --setopt=fedora.gpgcheck=1 fedora
============================================================== repo: fedora ==============================================================
Error: Error parsing '['1']': Wrong number or type of arguments for overloaded function 'OptionChildBool_set'.
  Possible C/C++ prototypes are:
    libdnf::OptionChild< libdnf::OptionBool >::set(libdnf::Option::Priority,libdnf::OptionBool::ValueType const &)
    libdnf::OptionChild< libdnf::OptionBool >::set(libdnf::Option::Priority,std::string const &)