multisig: Ignore untrusted signatures if there is trusted one
Ported from dnf commit: 00fef9ad0d761eccf8d86580e031f442af9cd8ef

With RPMv6 signatures, there can be multiple signatures attached to
a single package. If some signatures are made with an algorithm
disabled in a system-wide crypto policy (e.g. rsa4096 = "never" in
/etc/crypto-policies/back-ends/rpm-sequoia.config), but other
signatures are valid and trusted, so that the package is overall
correctly signed:

    # /usr/lib/pqrpm/bin/rpmkeys -v -K ./foo-0-1.fc43.noarch.rpm; echo $?
    ./foo-0-1.fc43.noarch.rpm:
	Header V4 EdDSA/SHA512 Signature, key ID e2b145f3: OK
	Header V4 RSA/SHA512 Signature, key ID b5e56945: NOTTRUSTED
	Header SHA256 digest: OK
	Header SHA1 digest: OK
	Payload SHA256 digest: OK
    0

DNF failed like this:

    [...]
    Is this ok [y/N]: y
    Downloading Packages:
    Running transaction check
    Transaction check succeeded.
    Running transaction test
    Transaction test succeeded.
    norsa                                                                  1.6 MB/s | 1.6 kB     00:00
    Importing GPG keys from: /root/repos/norsa/rsa.key
    Is this ok [y/N]: y
    Key import failed. Failing package is: foo-0-1.fc43.noarch
     GPG Keys are configured as: file:///root/repos/norsa/rsa.key, file:///root/repos/norsa/eddsa.key
    Error: GPG check FAILED

The cause was that an output of pqrpm's "rpmkeys -v -K" tool executed
indirectly by Multisig plugin was incorrectly parsed in
_process_rpm_output() function. That function assumed that only one
signature can exist and reported on any NOTTRUSTED record that the
package is not trustfully signed.

As a result, the plugin attempted to (re)import all the signing keys. But
importing a key with the disabled algorithm failed and DNF errored.

This patch fixes parsing the rpmkeys output to ignore all untrusted
signatures if there is at least one signature trusted.

Resolve: https://issues.redhat.com/browse/RHEL-145372