[config-manager] --setopt: Add check for existence of input repositories (RhBug:1702678)
Examples:
dnf config-manager --save --setopt=non_existent.key=value
Error: No matching repo to modify: non_existent.

dnf config-manager --save --setopt=non_existent*.key=value
Error: No matching repo to modify: non_existent*.

None change in configuration is done after the error.