generate_completion_cache: use list for each insert (fixes regression introduced in e020c96)
Traceback (most recent call last):
  File "/home/jsilhan/Documents/dnf/bin/dnf-2", line 36, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/home/jsilhan/Documents/dnf/dnf/cli/main.py", line 193, in user_main
    errcode = main(args)
  File "/home/jsilhan/Documents/dnf/dnf/cli/main.py", line 84, in main
    return _main(base, args)
  File "/home/jsilhan/Documents/dnf/dnf/cli/main.py", line 146, in _main
    ret = resolving(cli, base)
  File "/home/jsilhan/Documents/dnf/dnf/cli/main.py", line 178, in resolving
    base.plugins.run_transaction()
  File "/home/jsilhan/Documents/dnf/dnf/plugin.py", line 82, in fn
    dnf.util.mapall(operator.methodcaller(method), self.plugins)
  File "/home/jsilhan/Documents/dnf/dnf/util.py", line 157, in mapall
    return list(map(fn, *seq))
  File "/home/jsilhan/Documents/dnf-plugins-core/plugins/generate_completion_cache.py", line 85, in transaction
    inst_pkgs_insert)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 29 supplied.

Reported-by: Jan Silhan <jsilhan@redhat.com>
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>