multisig: Fix handling exceptions in RHEL 9 DNF
RHEL 9 DNF does not yet support
dnf.exceptions.InvalidInstalledGPGKeyError type. The support was
added in upstream commit eabf33aeeb486ec671f3e3fd2120bccc396d2326
("cli: Print a plugin suggestion on installed but expired pgp key").
Failed key import resulted in double-exception:

    Is this ok [y/N]: y
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/dnf-plugins/multisig.py", line 392, in gpgsigcheck
	self._get_key_for_package(po, fn)
      File "/usr/lib/python3.9/site-packages/dnf-plugins/multisig.py", line 340, in _get_key_for_package
	raise dnf.exceptions.Error(_prov_key_data(msg))
    dnf.exceptions.Error: Key import failed. Failing package is: foo-0-1.fc43.noarch
     GPG Keys are configured as: file:///root/repos/pq/both.keys

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/dnf/plugin.py", line 107, in _caller
	getattr(plugin, method)()
      File "/usr/lib/python3.9/site-packages/dnf-plugins/multisig.py", line 40, in pre_transaction
	self.gpgsigcheck(inbound_packages)
      File "/usr/lib/python3.9/site-packages/dnf-plugins/multisig.py", line 395, in gpgsigcheck
	if isinstance(e, dnf.exceptions.InvalidInstalledGPGKeyError):
    AttributeError: module 'dnf.exceptions' has no attribute 'InvalidInstalledGPGKeyError'

and the installation continued.

This patch removes the use of the dnf.exceptions.InvalidInstalledGPGKeyError()
feature.