kickstart: fix installing groups after API change (RhBug:1138414)
Traceback (most recent call last):
  File "/bin/dnf", line 36, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 182, in
user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 84, in
main
    return _main(base, args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 134, in
_main
    cli.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1072, in
run
    return self.command.run(self.base.extcmds)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/kickstart.py", line
101, in run
    self.base.install_grouplist(group_names)
AttributeError: 'BaseCli' object has no attribute 'install_grouplist'

API reference doesn't have `base.install_grouplist`, but we have
`base.group_install`. let's fix it!

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1138414